// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR3-K2vaQBG_PYaE1SeDAdSXbSp8BDluE',
    appId: '1:385049454690:web:d42c2926fb16663952493b',
    messagingSenderId: '385049454690',
    projectId: 'finnotix',
    authDomain: 'finnotix.firebaseapp.com',
    storageBucket: 'finnotix.firebasestorage.app',
    measurementId: 'G-PRH1QJNS7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDttA1-lc6n_DXT0wQ4OSSQ6Rzf-E2GRFA',
    appId: '1:385049454690:android:4b98e935b366d01152493b',
    messagingSenderId: '385049454690',
    projectId: 'finnotix',
    storageBucket: 'finnotix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAALHCZTLY5VmjeYSVQ3pSnqX6sdfsF1vA',
    appId: '1:385049454690:ios:e416c133da6e8d5c52493b',
    messagingSenderId: '385049454690',
    projectId: 'finnotix',
    storageBucket: 'finnotix.firebasestorage.app',
    iosBundleId: 'com.example.finnotix',
  );
}
